spring.application.name=todo-lis
spring.datasource.url=jdbc:h2:mem:todolist
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=admin
# O Hibernate 7+ (usado no Spring Boot 4) já detecta o dialeto do H2 automaticamente,
# mas se quiser manter, corrija a grafia aqui também:
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Ativação do Console do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console